# -*- coding: utf-8 -*-
"""func1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dw_p-qOL4ijhsT4bffZvp1FdElHM9qKi
"""

import ipywidgets as widgets
from IPython.display import display, clear_output

def voltage(current, resistance):
    return current * resistance

def power(voltage, current):
    return voltage * current

def run_experiment(I, R):
    clear_output(wait=True)

    V = voltage(I, R)
    P = power(V, I)

    print(f"[실험 결과]")
    print(f"전류: {I:.2f} A")
    print(f"저항: {R:.2f} Ω")
    print(f"전압: {V:.2f} V")
    print(f"전력: {P:.2f} W")

# 1. 전류 슬라이더 생성
current_slider = widgets.FloatSlider(
    value=2, min=0, max=10, step=0.5,
    orientation='vertical', description='전류(A)'
)

# 2. 저항 슬라이더 생성
resistance_slider = widgets.FloatSlider(
    value=5, min=1, max=20, step=1,
    orientation='vertical', description='저항(Ω)'
)

# 3. 레이아웃 구성: 슬라이더들을 가로로 묶고, 그 아래에 결과값(out) 배치
ui = widgets.HBox([current_slider, resistance_slider], layout=widgets.Layout(gap='30px'))

# 4. 최종 출력 (슬라이더 묶음 + 실행 결과)
display(ui)

# 인터랙션 연결
widgets.interactive(
    run_experiment,
    I=current_slider,
    R=resistance_slider
)

# 2. 인터랙션 연결 (화면에 출력되지 않고 연결만 함)
# 'I'와 'R'은 run_experiment 함수의 인자 이름과 일치해야 합니다.
out = widgets.interactive_output(
    run_experiment,
    {'I': current_slider, 'R': resistance_slider}
)

# 3. 레이아웃 구성: 슬라이더들을 가로로 묶고, 그 아래에 결과값(out) 배치
ui = widgets.HBox([current_slider, resistance_slider], layout=widgets.Layout(gap='30px'))

# 4. 최종 출력 (슬라이더 묶음 + 실행 결과)
display(ui, out)