# -*- coding: utf-8 -*-
"""game_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FI7ksLZ7qu_5uxLyaJx0DbKuaJQhPXIK

#간단한 게임
"""

import random
import time

# 1. 검사 함수: 정답 비교 및 상태 업데이트
def check_rainbow_wire(user_choice, secret_answer, current_life):
    print(f"\n [{user_choice}] 선을 조심스럽게 건드립니다...")
    time.sleep(1)

    if user_choice == secret_answer:
        return True, current_life
    else:
        current_life -= 1
        return False, current_life

# 2. 무지개 색상 및 정답 설정
rainbow_colors = ["빨강", "주황", "노랑", "초록", "파랑", "남색", "보라"]
bomb_answer = random.choice(rainbow_colors)

life = 3
is_defused = False

print("[MISSION] 무지개 선 중 단 하나만이 정답입니다!")
print("후보색상: ",rainbow_colors)

# 3. 게임 메인 루프
while life > 0:
    # 남은 목숨 시각화
    print("\n" + "♡ " * life + f" (남은 기회: {life}번)")

    user_input = input(f"어떤 색의 선을 자르시겠습니까? : ").strip()

    # 입력값 검증
    if user_input not in rainbow_colors:
        print(f"무지개 색상({rainbow_colors}) 중에서 입력해주세요!")
        continue

    # 함수 호출 및 결과 언패킹
    is_defused, life = check_rainbow_wire(user_input, bomb_answer, life)

    if is_defused:
        print("✨ 팅! 무지개 빛이 사라지며 폭탄이 정지되었습니다. 해체 성공!")
        break
    else:
        if life > 0:
            print(f" 콰광! [{user_input}]은 정답이 아닙니다. 폭발이 임박했습니다!")
            # 틀린 색상 제거
            rainbow_colors.remove(user_input)
            print(f"남은 가능성: {rainbow_colors}")

# 4. 최종 결과 출력
print("\n" + "=" * 20)
if is_defused:
    print("MISSION COMPLETE: 당신은 무지개 수호자입니다!")
else:
    print(f"GAME OVER: 정답은 [{bomb_answer}]였습니다. 도시가 무지개색으로 폭발했습니다.")
print("=" * 20)