# -*- coding: utf-8 -*-
"""game_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18qR1p-DvHWdFTwlv7eY9mxV_Rzs_6haL

#간단한 게임
"""

import random
import time
from IPython.display import clear_output

# 1. 판정 함수 (단순 비교만 수행)
def check_rainbow_wire(choice, answer, current_life):
    if choice == answer:
        return True, current_life
    else:
        current_life -= 1
        return False, current_life

# 2. 초기 세팅
rainbow_colors = ["빨강", "주황", "노랑", "초록", "파랑", "남색", "보라"]
bomb_answer = random.choice(rainbow_colors)
life = 3
is_defused = False
status_msg = "🚨 게임 시작! 무지개 선 중 하나를 선택하세요."

# 3. 게임 메인 루프
while life > 0:
    # 화면 갱신: 항상 정보가 먼저 보이고 그 아래 입력창이 생김
    clear_output(wait=True)
    print("=" * 45)
    print(f" 💬 상태: {status_msg}")
    print(f" 🎨 남은 후보: {', '.join(rainbow_colors)}")
    print(f" " + "❤️ " * life + f" (기회: {life}번)")
    print("=" * 45)

    # 입력 받기 (화면 맨 아래에 위치)
    user_input = input("잘라낼 선의 색깔을 입력하세요: ").strip()

    # 예외 처리
    if user_input not in rainbow_colors:
        status_msg = f"⚠️ [{user_input}]은(는) 목록에 없습니다. 다시 보세요!"
        continue

    # 판정 시작
    print(f"\n🔍 {user_input} 선을 검사 중...")
    time.sleep(1) # 사용자가 읽을 시간 확보

    is_defused, life = check_rainbow_wire(user_input, bomb_answer, life)

    if is_defused:
        status_msg = "✨ 성공! 폭탄이 해제되었습니다!"
        break
    else:
        status_msg = f"💥 꽝! [{user_input}]은 정답이 아닙니다!"
        rainbow_colors.remove(user_input)
        time.sleep(1.5) # 결과를 잠깐 보여주고 다음 루프로 이동

# 4. 최종 결과
clear_output(wait=True)
print("\n" + "🌈" * 20)
if is_defused:
    print(f"🎊 MISSION COMPLETE! 정답: [{bomb_answer}]")
    print("당신은 무지개 수호자입니다!")
else:
    print(f"💀 GAME OVER... 정답: [{bomb_answer}]")
print("🌈" * 20)