# -*- coding: utf-8 -*-
"""TTS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xKtSZ4lzknpBW19TlBxF3Rpq5Pwnn4a2

#TTS(Text to Speech)서비스
"""

# 음성 합성을 위한 라이브러리 설치
!pip install gTTS

# 2. 라이브러리 불러오기

# gTTS(Google Text-to-Speech):
# 문자열(String) 데이터를 음성 신호(Audio Data)로 합성하기 위한 라이브러리입니다.
# 클라우드 엔진을 거쳐 텍스트를 .mp3 파일로 변환하는 역할을 수행합니다.
from gtts import gTTS

# IPython.display (Audio, display):
# 코랩 환경(IPython 인터프리터)의 웹 인터페이스에서 멀티미디어 출력을 제어합니다.
# Audio: 저장된 .mp3 파일을 오디오 플레이어로 맵핑합니다.
# display: 생성된 오디오 플레이어 객체를 사용자 화면에 즉시 렌더링(시각화)합니다.
from IPython.display import Audio, display

# 3. 사용자로부터 텍스트 입력 받기
user_text = input("목소리로 바꾸고 싶은 문장을 입력하세요: ")

#4. gTTS를 이용하여 음성 생성및 저장

tts = gTTS(text=user_text, lang='ko', slow=False)
tts.save('output.mp3')

# 5. 코랩에서 즉시 재생
print(f"\n입력하신 내용: '{user_text}'")
Audio('output.mp3', autoplay=True)