# -*- coding: utf-8 -*-
"""키오스크.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O2MBgJ6Z8fEjBNYgYX17w8sXsPhE_g5c
"""

# 1. 메뉴 데이터 (딕셔너리)
menu_data = {
    1: {"이름": "김밥", "가격": 3000},
    2: {"이름": "떡볶이", "가격": 5000},
    3: {"이름": "라면", "가격": 5000}
}

# 2. 주문 내역을 담을 빈 딕셔너리 (메뉴명: 수량)
order_list = {}

print("--- [분식점 키오스크] ---")
for num, info in menu_data.items():
    print(f"{num}. {info['이름']} ({info['가격']}원)")
print("0. 주문 종료 및 계산")
print("-----------------------")

# 3. 주문 루프
while True:
    choice = input("\n구매하실 메뉴 번호를 입력하세요: ")

    # 입력값이 숫자인지 확인
    if not choice.isdigit():
        print("숫자로만 입력해 주세요.")
        continue

    choice = int(choice)

    # 0번을 누르면 주문 종료
    if choice == 0:
        break

    # 메뉴 번호가 딕셔너리에 있는지 확인
    if choice in menu_data:
        selected_menu = menu_data[choice]["이름"]

        count = input(f"[{selected_menu}] 몇 개 주문하시겠습니까? ")
        if not count.isdigit():
            print("수량은 숫자로 입력해야 합니다. 다시 선택해 주세요.")
            continue

        count = int(count)
        if count <= 0:
            print("1개 이상 주문해 주세요.")
            continue

        # 장바구니(order_list)에 추가 또는 합산
        if selected_menu in order_list:
            order_list[selected_menu] += count
        else:
            order_list[selected_menu] = count

        print(f"> {selected_menu} {count}개가 추가되었습니다.")
    else:
        print("없는 번호입니다. 메뉴판의 번호를 확인해 주세요.")

# 4. 최종 결과 출력
print("\n" + "="*30)
print("       [ 최종 주문 내역 ]")
print("-"*30)

total_sum = 0
for name, amount in order_list.items():
    # 메뉴 이름을 통해 가격 찾아오기 (단가 계산용)
    price = 0
    for m in menu_data.values():
        if m["이름"] == name:
            price = m["가격"]

    subtotal = price * amount
    total_sum += subtotal
    print(f"{name:.<10}{amount}개 : {subtotal:>6}원")

print("-"*30)
print(f"총 결제 금액: {total_sum:>15}원")
print("="*30)
print("맛있게 준비해 드리겠습니다!")